runtime: nodejs18
instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65 # Adjust as necessary
  min_instances: 1 # Optional: Set a minimum number of instances
  max_instances: 2 # Set a maximum number of instances
